spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Shifeng941121.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.ysf.blog: debug
  file: log/blog-dev.log